Repository Team-8px/earth_market, pull requests merged in 2022-03, with the labels that each got.

#108 Fix: 태그 위치 변경
  src/components/Profile/ProductContainer/index.jsx
Labels: 🛠 Refactoring

#109 Refactor: 로그인페이지 리팩토링 및 로그인된 유저 예외처리 구현
  src/App.js
  src/PAGE/LoginMain.jsx
  src/PAGE/YourProfile.jsx
  src/components/module/Text/LoginText.js
Labels: 🪄 Feat, 🛠 Refactoring

#110 Refector: post container
  src/PAGE/MyProfile.jsx
  src/PAGE/MyProfileJY.jsx
  src/components/Profile작업/AlbumGallery/index.jsx
  src/components/Profile작업/AlbumGallery/index.style.js
  src/components/Profile작업/CardGallery/index.jsx
  src/components/Profile작업/CardGallery/index.style.js
  src/components/Profile작업/GalleryContainer/index.jsx
  src/components/Profile작업/GalleryContainer/index.style.js
  src/components/Profile작업/PostViewCard/index.jsx
  src/components/Profile작업/PostViewCard/index.style.js
  src/components/Profile작업/ProductCard/index.jsx
  src/components/Profile작업/ProductCard/index.style.js
  src/components/Profile작업/ProductContainer/index.jsx
  src/components/Profile작업/ProductContainer/index.style.js
  src/components/Profile작업/ProfileCard/index.jsx
  src/components/Profile작업/ProfileCard/index.style.js
  src/components/Profile작업/ProfileContainer/index.jsx
  src/components/Profile작업/ProfileContainer/index.style.js
Labels: 🛠 Refactoring

#111 Refactoring: follow
  src/PAGE/FollowerList.jsx
  src/PAGE/FollowingList.jsx
  src/components/Profile작업/FollowerCard/index.jsx
  src/components/Profile작업/FollowerCard/index.style.js
  src/components/Profile작업/FollowerContainer/index.jsx
  src/components/Profile작업/FollowerContainer/index.style.js
  src/components/Profile작업/FollowingCard/index.style.js
  src/components/Profile작업/FollowingCard/inex.jsx
  src/components/Profile작업/FollowingContainer/index.jsx
  src/components/Profile작업/FollowingContainer/index.style.js
Labels: 🛠 Refactoring

#114 Refactoring: search
  src/PAGE/MyProfileJY.jsx
  src/PAGE/Search.jsx
  src/components/profile/ProfileContainer/index.jsx
  src/components/search/SearchBar/index.jsx
  src/components/search/SearchBar/index.style.js
  src/components/search/SearchCard/index.jsx
  src/components/search/SearchCard/index.style.js
  src/components/search/SearchContainer/index.jsx
  src/components/search/SearchContainer/index.style.js
Labels: 🛠 Refactoring

#115 리팩토링 : 조인 프로필
  src/App.js
  src/PAGE/Join-JS.jsx
  src/components/Join 작업/JoinMember/index.jsx
  src/components/Join 작업/JoinMember/index.style.js
  src/components/Join 작업/JoinProfile/index.jsx
  src/components/Join 작업/JoinProfile/index.style.js
Labels: 🛠 Refactoring

#117 fix : 오류 해결
  src/components/Join 작업/JoinProfile/index.jsx
Labels: 🛠 Refactoring

#120 Refactor: 회원가입 모듈 분리
  src/App.js
  src/PAGE/Join-JS.jsx
  src/actions/userActions.js
  src/components/Join 작업/JoinMember/index.jsx
  src/components/Join 작업/JoinProfile/index.jsx
Labels: 🛠 Refactoring

#122 Refactoring : Login main
  src/App.js
  src/PAGE/LoginMain-JS.jsx
  src/components/Login/index.jsx
  src/components/Login/index.style.js
  src/styles/theme.js
Labels: 🛠 Refactoring

#123 fix: 폴더이름 변경
  src/components/Join/JoinMember/index.jsx
  src/components/Join/JoinMember/index.style.js
  src/components/Join/JoinProfile/index.jsx
  src/components/Join/JoinProfile/index.style.js
Labels: 🛠 Refactoring

#121 Refactoring: header container
  src/App.js
  src/PAGE/MyProfile.jsx
  src/components/common/CommonHeader/index.jsx
  src/components/common/CommonHeader/index.style.js
Labels: 🛠 Refactoring

#125 Refactoring: header component
  src/PAGE/FollowerList.jsx
  src/PAGE/FollowingList.jsx
  src/PAGE/Home.jsx
  src/components/header/FollowHeader/index.jsx
  src/components/header/FollowHeader/index.style.js
  src/components/header/HomeHeader/index.jsx
  src/components/header/HomeHeader/index.style.js
Labels: 🛠 Refactoring

#127 Refactor: post upload 모듈 분리
  src/App.js
  src/PAGE/PostUpload.jsx
  src/PAGE/PostUploadMJ.jsx
  src/actions/postActions.js
  src/components/PostUpload/PostUploadForm/index.jsx
  src/components/PostUpload/PostUploadForm/index.style.js
  src/components/Upload/UploadPage/index.jsx
  src/components/Upload/UploadPage/index.style.js
Labels: 🛠 Refactoring

#126 Refactoring : Login main button
  src/components/Login/index.jsx
  src/components/Login/index.style.js
Labels: 🛠 Refactoring

#129 Refactoring: splash screen
  src/App.js
  src/PAGE/LoginMain-JS.jsx
  src/PAGE/LoginMainTEST.jsx
  src/PAGE/SplashScreen.jsx
  src/components/Alert.js
  src/components/Login/LoginCard/index.jsx
  src/components/Login/LoginCard/index.style.js
  src/components/Login/LoginContainer/index.jsx
  src/components/Login/LoginContainer/index.style.js
  src/components/Login/SplashCard/index.jsx
  src/components/Login/SplashCard/index.style.js
  src/components/Login/index.jsx
Labels: 🛠 Refactoring

#130 Refactoring: splash screen 재영님과 쉐어프로그래밍
  src/components/Login/LoginCard/index.jsx
  src/components/Login/LoginCard/index.style.js
  src/components/Login/LoginContainer/index.jsx
  src/components/Login/LoginContainer/index.style.js
  src/components/Login/SplashCard/index.style.js
  src/components/module/logo/LoginLogo.js
Labels: :office: Build

#133 Refactoring: add animation img
  src/asset/full-logo-white.svg
  src/components/Login/LoginCard/index.style.js
  src/components/Login/SplashCard/index.jsx
  src/components/Login/SplashCard/index.style.js
Labels: 🛠 Refactoring

#134 add:
  src/App.js
  src/PAGE/PostUpload.jsx
  src/PAGE/ProductUploadMJ.jsx
  src/components/PostUpload/index.jsx
  src/components/PostUpload/index.style.js
  src/components/ProductUpload/index.jsx
  src/components/ProductUpload/index.style.js
  src/components/common/UploadHeader/index.jsx
  src/components/common/UploadHeader/index.style.js
  src/components/profile/ProfileContainer/index.jsx
  src/util/markingPriceFormat.js
Labels: 🪄 Feat

#135 Refactoring: Home&Router
  src/App.js
  src/PAGE/Home.jsx
  src/PAGE/LoginMain.jsx
  src/PAGE/LoginMainTEST.jsx
  src/components/Login/LoginCard/index.style.js
  src/components/Login/SplashCard/index.jsx
  src/components/Login/SplashCard/index.style.js
  src/components/common/PostCard/index.jsx
  src/components/common/PostCard/index.style.js
  src/components/home/HomeContainer/index.jsx
  src/components/home/HomeContainer/index.style.js
  src/components/profile/AlbumGallery/index.style.js
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProfileContainer/index.jsx
Labels: 🛠 Refactoring

#137 Refactoring: profile 라우팅 분기 작업
  src/App.js
  src/PAGE/MyProfile.jsx
  src/PAGE/ProductUpdateMJ.jsx
  src/PAGE/ProductUpload.jsx
  src/PAGE/ProductUploadMJ.jsx
  src/components/Upload/ProductEditPage/index.jsx
  src/components/productupdate/index.jsx
  src/components/productupdate/index.style.js
  src/components/profile/ProfileContainer/index.jsx
Labels: 🛠 Refactoring

#138 Add: YourProfile 팔로우 버튼 추가
  src/components/profile/ProfileCard/index.jsx
  src/components/profile/ProfileCard/index.style.js
Labels: 🛠 Refactoring

#136 Refactoring: LoginMain 스타일링
  src/asset/full-logo-blue.png
  src/asset/full-logo-white.png
  src/asset/full-logo.svg
  src/asset/icon/icon-email.svg
  src/asset/icon/icon-login.svg
  src/components/Login/LoginCard/index.jsx
  src/components/Login/LoginCard/index.style.js
  src/components/Login/SplashCard/index.style.js
  src/styles/GlobalStyles.js
  src/styles/font.css
Labels: 🎨 Design, 🛠 Refactoring

#139 add: 사용자 인증을 구분하는 공통함수 구현
  src/App.js
  src/PAGE/MyProfile.jsx
  src/actions/postActions.js
  src/actions/productActions.js
  src/actions/userActions.js
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProductContainer/index.jsx
  src/components/profile/ProfileCard/index.jsx
  src/components/profile/ProfileContainer/index.jsx
  src/hooks/useWhichUserAccountName.js
  src/hooks/useWhichUserStatus.js
  src/util/getWhichUser.js
  src/util/towardLinkAddress.js
Labels: :office: Build

#140 fix: profile 부분 페이지 이동시 리랜더링 오류
  src/App.js
  src/actions/followAction.js
  src/components/common/Navbar/index.jsx
  src/components/common/PostCard/index.jsx
  src/components/follow/FollowerContainer/index.jsx
  src/components/follow/FollowingContainer/index.jsx
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProductContainer/index.jsx
  src/components/profile/ProfileCard/index.jsx
  src/components/profile/ProfileContainer/index.jsx
  src/components/template/common/Navigation.js
  src/util/getWhichUser.js
  src/util/towardLinkAddress.js
Labels: 🐛 Fix Bug

#141 Refactoring: routing and activity
  src/App.js
  src/PAGE/LoginEmail.jsx
  src/PAGE/NotFound.jsx
  src/components/Login/LoginContainer/index.jsx
  src/components/etc/NotFoundContainer/index.jsx
  src/components/etc/NotFoundContainer/index.style.js
  src/components/template/screen/NotFound.js
  src/components/template/screen/SplashScreen.js
Labels: 🐛 Fix Bug, 🛠 Refactoring

#142 Refactoring: styling
  src/components/home/HomeContainer/index.style.js
Labels: 🛠 Refactoring

#147 add: 기본이미지 변경 함수 추상화
  src/App.js
  src/components/search/SearchContainer/index.jsx
  src/util/changeDefaltImage.js
Labels: 🪄 Feat

#149 Refactoring: styling, file
  src/components/PostUpload/index.style.js
  src/components/follow/FollowerCard/index.jsx
  src/components/follow/FollowerCard/index.style.js
  src/components/follow/FollowerContainer/index.jsx
  src/components/follow/FollowingCard/index.style.js
  src/components/follow/FollowingCard/inex.jsx
  src/components/follow/FollowingContainer/index.jsx
  src/components/home/HomeContainer/index.jsx
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProfileContainer/index.jsx
  src/components/search/SearchContainer/index.jsx
Labels: 🛠 Refactoring, :office: Build

#150 add: input value update
  src/App.js
  src/PAGE/MyProfile-gh.jsx
  src/PAGE/ProductUpdate.jsx
  src/PAGE/ProductUpdateMJ.jsx
  src/PAGE/Profile.jsx
  src/actions/productActions.js
  src/components/ProductUpload/index.jsx
  src/components/productupdate/index.jsx
Labels: 🪄 Feat

#151 Refactoring api
  src/App.js
  src/PAGE/Information.jsx
  src/components/etc/Error/index.jsx
  src/components/etc/Error/index.style.js
  src/components/etc/Loading/index.jsx
  src/components/etc/Loading/index.style.js
  src/components/information/InformationCard/index.jsx
  src/components/information/InformationCard/index.style.js
  src/components/information/InformationContainer/index.jsx
  src/components/information/InformationContainer/index.style.js
  src/hooks/usePromise.js
Labels: 🛠 Refactoring

#152 Refactoring: delete file & 기능 수정
  src/PAGE/LoginEmail.jsx
  src/components/ChatInfoList.js
  src/components/Comment.js
  src/components/Login/LoginContainer/index.jsx
  src/components/SubmitChat.js
  src/components/Upload.js
  src/components/common/PostCard/index.jsx
  src/components/common/PostCard/index.style.js
  src/components/common/image/ProfileImageStyle.js
  src/components/module/Text/EmailText.js
  src/components/module/Text/LoginText.js
  src/components/module/Text/SubText.js
  src/components/module/chat/Chat.js
  src/components/module/comment/Conment.js
  src/components/module/form/LoginForm.js
  src/components/module/form/ProductForm.js
  src/components/module/form/ProfileForm.js
  src/components/module/form/RegisterForm.js
  src/components/module/handler/AlbumHandler.js
  src/components/module/logo/HomeLogo.js
  src/components/module/logo/LoginLogo.js
  src/components/module/logo/NotFoundLogo.js
  src/components/module/logo/SplashLogo.js
  src/components/module/post/ImageBox.js
  src/components/module/product/Product.js
  src/components/module/profile/DisplayButton.js
  src/components/module/profile/MyUserInfo.js
  src/components/module/profile/ProfileIUpload.js
  src/components/module/profile/YourUserInfo.js
  src/components/module/title/EmailTitle.js
  src/components/module/title/LoginTitle.js
  src/components/module/title/ProfileTitle.js
  src/components/module/user/ChatListUser.js
  src/components/module/user/CommentUser.js
  src/components/module/user/FollowersUser.js
  src/components/module/user/ReplyUser.js
  src/components/module/user/SearchUser.js
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProfileCard/index.jsx
Labels: 🐛 Fix Bug, 🛠 Refactoring

#153 Refactoring: delete file & LoginEmail page 작업
  package-lock.json
  package.json
  src/App.js
  src/PAGE/JoinProfile.jsx
  src/PAGE/LoginEmailJS.jsx
  src/asset/8px.png
  src/asset/Ellipse 6.png
  src/asset/Ellipse-1.png
  src/asset/basic-profile-img.png
  src/asset/chat-exapmle.png
  src/asset/facebook.svg
  src/asset/full-logo.png
  src/asset/google.png
  src/asset/google.svg
  src/asset/icon/8px.png
  src/asset/icon/favicon.ico
  src/asset/symbol-logo-W.png
  src/asset/symbol-logo-W.svg
  src/components/Login/LoginEmail/index.jsx
  src/components/Login/LoginEmail/index.style.js
  src/components/PostView/CommentCard/index.jsx
  src/components/common/image/ProfileImageStyle.js
  src/components/module/button/button.js
  src/components/module/post/ReplyBox.js
  src/styles/theme.js
Labels: 🛠 Refactoring

#154 add: 프로필 수정 input value change 기능 추가
  src/App.js
  src/PAGE/ProfileUpdate.jsx
  src/actions/userActions.js
  src/components/profile/ProfileCard/index.jsx
  src/components/profileupdate/index.jsx
  src/components/profileupdate/index.style.js
Labels: 🪄 Feat

#155 Edit : 로그인 타이틀 수정
  src/components/Login/LoginEmail/index.jsx
  src/components/module/button/button.js
Labels: 🛠 Refactoring

#156 Refactoring: 이미지 파일 불러오기 성공
  src/components/information/InformationContainer/index.jsx
  src/hooks/usePromise.js
Labels: 🐛 Fix Bug, 🛠 Refactoring

#157 Refactoring: modal alert
  src/components/Alert.js
  src/components/HiddenMenu.js
  src/components/common/Alert/index.jsx
  src/components/common/Alert/index.style.js
  src/components/common/CommonHeader/index.jsx
  src/components/common/Modal/index.jsx
  src/components/common/Modal/index.style.js
  src/components/home/HomeContainer/index.jsx
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProductContainer/index.jsx
Labels: 🛠 Refactoring

#158 fix: postUpload, postUpdate UI 오류 수정
  package-lock.json
  package.json
  src/App.js
  src/actions/postActions.js
  src/actions/userActions.js
  src/components/PostUpload/index.jsx
  src/components/PostView/CommentCard/index.jsx
  src/components/PostView/PostViewContainer/index.jsx
  src/components/ProductUpload/index.style.js
  src/components/common/Navbar/index.jsx
  src/components/common/PostCard/index.jsx
  src/components/common/PostIconBox/index.jsx
  src/components/common/PostIconBox/index.style.js
  src/components/module/post/IconBox.js
  src/components/productupdate/index.jsx
  src/components/productupdate/index.style.js
  src/constants/postConstants.js
  src/reducers/postReducers.js
  src/store.js
  src/util/getWhichUser.js
Labels: 🐛 Fix Bug

#161 Refactoring: Alert&Modal 미완작업 완료
  src/components/PostView/CommentCard/index.jsx
  src/components/PostView/PostViewContainer/index.jsx
Labels: 🛠 Refactoring

#162 add: post, product 삭제 기능 구현
  src/actions/postActions.js
  src/actions/productActions.js
  src/actions/userActions.js
  src/components/PostUpload/index.jsx
  src/components/PostView/CommentCard/index.jsx
  src/components/PostView/PostViewContainer/index.jsx
  src/components/common/PostCard/index.jsx
  src/components/common/PostIconBox/index.jsx
  src/components/module/post/ReplyBox.js
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProductCard/index.jsx
  src/components/profile/ProductContainer/index.jsx
  src/components/profile/ProfileContainer/index.jsx
  src/components/profileupdate/index.jsx
  src/util/getWhichUser.js
Labels: 🪄 Feat

#163 Refactoring: 상세게시글 슬라이더 구현 및 수정 디테일 추가 및 오전회의사항 반영
  src/components/PostView/PostViewContainer/index.jsx
  src/components/PostView/PostViewContainer/index.style.js
  src/components/common/PostCard/index.jsx
  src/components/common/PostCard/index.style.js
  src/components/common/PostIconBox/index.jsx
  src/components/common/PostIconBox/index.style.js
  src/components/profile/GalleryContainer/index.style.js
  src/components/profile/ProductCard/index.style.js
Labels: 🐛 Fix Bug, 🛠 Refactoring

#164 Edit: 디테일 수정
  src/components/common/PostCard/index.style.js
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/GalleryContainer/index.style.js
  src/styles/GlobalStyles.js
Labels: 🛠 Refactoring

#166 add: profile 부분 팔로우, 언팔로우 기능 추가
  src/components/follow/FollowerContainer/index.jsx
  src/components/profile/ProfileCard/index.jsx
  src/components/profile/ProfileCard/index.style.js
  src/components/profile/ProfileContainer/index.jsx
  src/constants/followConstants.js
  src/reducers/userReducers.js
Labels: 🪄 Feat

#167 Refactoring: NavLink 적용 완료
  src/components/common/Navbar/index.jsx
  src/components/common/Navbar/index.style.js
Labels: 🛠 Refactoring

#172 fix: url 변경
  src/constants/defaultUrl.js
Labels: ⚙️ Setting

#173 fix: http 서버 url로 다시 변경
  src/constants/defaultUrl.js
Labels: 🐛 Fix Bug

#174 Add: Information 페이지 추가
  src/App.js
  src/PAGE/Information.jsx
  src/components/common/Navbar/index.jsx
  src/components/header/InformationHeader/index.jsx
  src/components/header/InformationHeader/index.style.js
  src/components/information/InformationCard/index.jsx
  src/components/information/InformationCard/index.style.js
  src/components/information/InformationContainer/index.jsx
  src/components/information/InformationContainer/index.style.js
  src/components/search/SearchCard/index.style.js
Labels: 🪄 Feat, 🎨 Design

#175 fix: http 관련 오류
  public/index.html
Labels: 🐛 Fix Bug

#177 Style: 스타일 디테일 적용
  src/asset/icon/icon-heart-active.png
  src/asset/icon/icon-heart-active.svg
  src/components/Join/JoinProfile/index.style.js
  src/components/Login/LoginEmail/index.style.js
  src/components/PostUpload/index.style.js
  src/components/ProductUpload/index.style.js
  src/components/Upload/ProductPage/index.style.js
  src/components/common/Alert/index.style.js
  src/components/common/Modal/index.style.js
  src/components/common/Navbar/index.jsx
  src/components/common/Navbar/index.style.js
  src/components/common/PostCard/index.style.js
  src/components/common/PostIconBox/index.style.js
  src/components/etc/NotFoundContainer/index.style.js
  src/components/follow/FollowerCard/index.style.js
  src/components/follow/FollowerContainer/index.style.js
  src/components/follow/FollowingContainer/index.style.js
  src/components/header/FollowHeader/index.style.js
  src/components/header/HomeHeader/index.jsx
  src/components/header/HomeHeader/index.style.js
  src/components/header/InformationHeader/index.style.js
  src/components/home/HomeContainer/index.jsx
  src/components/home/HomeContainer/index.style.js
  src/components/information/InformationCard/index.style.js
  src/components/information/InformationContainer/index.style.js
  src/components/profile/AlbumGallery/index.style.js
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/GalleryContainer/index.style.js
  src/components/profile/ProfileCard/index.jsx
  src/components/profile/ProfileCard/index.style.js
  src/components/profileupdate/index.style.js
  src/components/search/SearchBar/index.style.js
  src/components/search/SearchCard/index.style.js
  src/components/search/SearchContainer/index.style.js
Labels: 🎨 Design

#179 add: 이미지 미리보기 삭제 기능 추가
  src/App.js
  src/PAGE/LoginEmail.jsx
  src/PAGE/LoginEmailJS.jsx
  src/components/PostUpload/index.jsx
Labels: 🪄 Feat

#180 Refactoring: delete never use
  src/PAGE/Join.jsx
  src/components/Join/JoinMember/index.jsx
  src/components/Join/JoinProfile/index.jsx
  src/components/Login/LoginContainer/index.jsx
  src/components/Login/LoginEmail/index.jsx
  src/components/PostView/CommentItem/index.jsx
  src/components/PostView/PostViewContainer/index.jsx
  src/components/common/PostIconBox/index.jsx
  src/components/follow/FollowerContainer/index.jsx
  src/components/follow/FollowingContainer/index.jsx
  src/components/information/InformationContainer/index.jsx
  src/components/profile/ProfileCard/index.style.js
  src/components/search/SearchBar/index.jsx
Labels: 🐛 Fix Bug, 🛠 Refactoring

#181 add: postupdate component 추가
  src/App.js
  src/actions/postActions.js
  src/components/postupdate/index.jsx
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProfileContainer/index.jsx
  src/constants/postConstants.js
  src/reducers/postReducers.js
  src/store.js
Labels: 🪄 Feat

#182 fix: 회원가입 시 프로필사진, 인트로 미등록 문제해결
  src/PAGE/Join.jsx
  src/PAGE/LoginMain.jsx
  src/actions/productActions.js
  src/actions/userActions.js
Labels: 🐛 Fix Bug

#183 Add : 댓글 프로필이미지 스타일링
  src/components/PostView/CommentCard/index.style.js
Labels: 🎨 Design

#184 Refactoring : 스타일링 변경, 프로필 이미지 추가
  src/components/PostView/CommentCard/index.jsx
  src/components/PostView/CommentCard/index.style.js
  src/components/common/Navbar/index.style.js
  src/components/search/SearchBar/index.style.js
  src/components/search/SearchCard/index.jsx
  src/components/search/SearchCard/index.style.js
Labels: 🎨 Design, 🛠 Refactoring

#186 Refactoring: react modal click outside
  src/components/PostUpload/index.jsx
  src/components/PostUpload/index.style.js
  src/components/PostView/CommentCard/index.jsx
  src/components/PostView/PostViewContainer/index.jsx
  src/components/common/CommonHeader/index.jsx
  src/components/common/Modal/index.jsx
  src/components/home/HomeContainer/index.jsx
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProductContainer/index.jsx
Labels: 🐛 Fix Bug, 🛠 Refactoring

#185 Refactoring: 시맨틱 마크업 적용 및 스타일 변경
  src/components/Join/JoinMember/index.jsx
  src/components/Join/JoinMember/index.style.js
  src/components/Join/JoinProfile/index.jsx
  src/components/Join/JoinProfile/index.style.js
  src/components/Login/LoginCard/index.jsx
  src/components/Login/LoginCard/index.style.js
  src/components/Login/LoginContainer/index.jsx
  src/components/Login/LoginContainer/index.style.js
  src/components/Login/LoginEmail/index.jsx
  src/components/Login/LoginEmail/index.style.js
  src/components/Login/SplashCard/index.jsx
  src/components/Login/SplashCard/index.style.js
  src/components/Upload/ProductPage/index.style.js
  src/components/common/CommonHeader/index.jsx
  src/components/common/CommonHeader/index.style.js
  src/components/common/PostCard/index.jsx
  src/components/common/PostCard/index.style.js
  src/components/follow/FollowerCard/index.jsx
  src/components/follow/FollowerCard/index.style.js
  src/components/follow/FollowerContainer/index.style.js
  src/components/follow/FollowingCard/index.jsx
  src/components/follow/FollowingCard/index.style.js
  src/components/follow/FollowingContainer/index.jsx
  src/components/follow/FollowingContainer/index.style.js
  src/components/header/FollowHeader/index.jsx
  src/components/header/FollowHeader/index.style.js
  src/components/header/HomeHeader/index.jsx
  src/components/header/HomeHeader/index.style.js
  src/components/header/InformationHeader/index.jsx
  src/components/header/InformationHeader/index.style.js
  src/components/home/HomeContainer/index.jsx
  src/components/home/HomeContainer/index.style.js
  src/components/information/InformationCard/index.jsx
  src/components/information/InformationCard/index.style.js
  src/components/information/InformationContainer/index.style.js
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/GalleryContainer/index.style.js
  src/components/profile/ProductCard/index.jsx
  src/components/profile/ProductCard/index.style.js
  src/components/profile/ProductContainer/index.jsx
  src/components/profile/ProductContainer/index.style.js
  src/components/profile/ProfileCard/index.jsx
  src/components/profile/ProfileCard/index.style.js
  src/components/profile/ProfileContainer/index.jsx
  src/components/profile/ProfileContainer/index.style.js
  src/components/search/SearchBar/index.jsx
  src/components/search/SearchBar/index.style.js
  src/components/search/SearchCard/index.jsx
  src/components/search/SearchCard/index.style.js
  src/components/search/SearchContainer/index.style.js
Labels: 🎨 Design, 🛠 Refactoring

#188 Refactoring: 유저리스트 간격 조정
  src/components/search/SearchCard/index.style.js
Labels: 🐛 Fix Bug, 🛠 Refactoring

#189 Refactoring: PostView페이지 Profile Img 불러오기
  src/components/PostView/CommentCard/index.jsx
  src/components/PostView/PostViewContainer/index.jsx
  src/util/getWhichUser.js
Labels: 🐛 Fix Bug, 🛠 Refactoring

#190 Refactoring: 시맨틱 태그 및 웹 접근성 고려
  src/PAGE/Home.jsx
  src/PAGE/Information.jsx
  src/PAGE/Profile.jsx
  src/PAGE/Search.jsx
  src/components/PostUpload/index.jsx
  src/components/PostUpload/index.style.js
  src/components/PostView/CommentCard/index.jsx
  src/components/ProductUpload/index.jsx
  src/components/ProductUpload/index.style.js
  src/components/Upload/EditPage/index.jsx
  src/components/Upload/ProductPage/index.jsx
  src/components/common/PostCard/index.jsx
  src/components/common/PostCard/index.style.js
  src/components/common/PostIconBox/index.style.js
  src/components/header/InformationHeader/index.jsx
  src/components/header/InformationHeader/index.style.js
  src/components/information/InformationCard/index.jsx
  src/components/information/InformationCard/index.style.js
  src/components/information/InformationContainer/index.jsx
  src/components/information/InformationContainer/index.style.js
  src/components/productupdate/index.jsx
  src/components/profile/ProfileCard/index.style.js
  src/components/profileupdate/index.jsx
  src/components/profileupdate/index.style.js
  src/components/search/SearchBar/index.jsx
  src/components/search/SearchBar/index.style.js
  src/styles/GlobalStyles.js
Labels: 🪄 Feat, 🎨 Design, 🛠 Refactoring

#192 add: 농민뉴스 크롤링 데이터 바인딩
  src/PAGE/Information.jsx
  src/actions/crawlingAction.js
  src/components/home/HomeContainer/index.jsx
  src/components/information/InformationCard/index.jsx
  src/components/information/InformationCard/index.style.js
  src/components/information/InformationContainer/index.jsx
  src/reducers/crawlingReducer.js
  src/util/crawlingNews.js
Labels: 🪄 Feat

#193 fix: 농민뉴스 타겟 url 변경
  src/actions/crawlingAction.js
  src/components/information/InformationCard/index.jsx
  src/constants/defaultUrl.js
Labels: 🛠 Refactoring

#196 Bd component info
  src/App.js
  src/components/Upload/EditPage/index.jsx
  src/components/Upload/EditPage/index.style.js
  src/components/Upload/ProductPage/index.jsx
  src/components/Upload/ProductPage/index.style.js
  src/components/Upload/UploadHeader/index.jsx
  src/components/Upload/UploadHeader/index.style.js
  src/components/information/InformationCard/index.jsx
  src/components/information/InformationContainer/index.jsx
  src/constants/defaultUrl.js
  src/hooks/usePromise.js
  src/pages/FollowerList.jsx
  src/pages/FollowingList.jsx
  src/pages/Home.jsx
  src/pages/Information.jsx
  src/pages/Join.jsx
  src/pages/LoginEmail.jsx
  src/pages/LoginMain.jsx
  src/pages/NotFound.jsx
  src/pages/PostUpdate.jsx
  src/pages/PostUpload.jsx
  src/pages/PostView.jsx
  src/pages/ProductUpdate.jsx
  src/pages/ProductUpload.jsx
  src/pages/Profile.jsx
  src/pages/ProfileUpdate.jsx
  src/pages/Search.jsx
Labels: 🪄 Feat

#197 Refactoring: Information 반응형, Update 페이지 통일성
  src/components/PostUpload/index.jsx
  src/components/PostUpload/index.style.js
  src/components/PostView/CommentCard/index.jsx
  src/components/PostView/CommentCard/index.style.js
  src/components/ProductUpload/index.jsx
  src/components/ProductUpload/index.style.js
  src/components/Upload/EditPage/index.jsx
  src/components/Upload/ProductPage/index.jsx
  src/components/common/PostCard/index.jsx
  src/components/information/InformationCard/index.style.js
  src/components/postupdate/index.jsx
  src/components/postupdate/index.style.js
  src/components/productupdate/index.jsx
  src/components/productupdate/index.style.js
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProductContainer/index.style.js
  src/components/profile/ProfileContainer/index.jsx
  src/components/profileupdate/index.jsx
  src/components/search/SearchBar/index.jsx
  src/components/search/SearchBar/index.style.js
  src/pages/FollowerList.jsx
  src/pages/FollowingList.jsx
  src/pages/Information.jsx
  src/styles/GlobalStyles.js
Labels: 🎨 Design, 🛠 Refactoring

#198 Refactoring: 경로 설정 문제 해결
  src/pages/Join.jsx
  src/pages/LoginEmail.jsx
  src/pages/LoginMain.jsx
  src/pages/PostView.jsx
Labels: 🐛 Fix Bug

#199 fix: 경로 수정
  src/components/Join/JoinMember/index.jsx
  src/components/Join/JoinProfile/index.jsx
  src/components/Upload/EditPage/index.jsx
  src/components/Upload/ProductPage/index.jsx
  src/components/postupdate/index.jsx
  src/pages/PostUpload.jsx
  src/pages/PostView.jsx
  src/pages/ProductUpload.jsx
Labels: 🐛 Fix Bug

#201 Refactoring: clean code
  src/components/common/Modal/index.style.js
  src/components/common/Navbar/index.style.js
  src/components/common/PostIconBox/index.jsx
  src/components/follow/FollowingContainer/index.jsx
  src/components/home/HomeContainer/index.jsx
  src/components/join/JoinMember/index.jsx
  src/components/login/LoginEmail/index.jsx
  src/components/postUpdate/index.jsx
  src/components/postUpload/index.jsx
  src/components/postView/CommentCard/index.jsx
  src/components/postView/PostViewContainer/index.jsx
  src/components/postView/PostViewContainer/index.style.js
  src/components/productUpdate/index.jsx
  src/components/profile/GalleryContainer/index.jsx
  src/components/profile/ProductContainer/index.jsx
  src/components/profile/ProfileContainer/index.jsx
  src/components/profileUpdate/index.style.js
  src/components/search/SearchBar/index.jsx
  src/styles/GlobalStyles.js
  src/styles/theme.js
Labels: 🐛 Fix Bug, 🛠 Refactoring
