Repository Team-8px/earth_market, pull requests merged in 2022-02, with the labels that each got.

#39 Fix: 작업환경 재구성 및 라우팅 환경 구성
  src/App.js
  src/components/module/button/button.js
  src/components/module/title/LoginTitle.js
  src/components/template/chat/ChatList.js
  src/components/template/chat/ChatRoom.js
  src/components/template/common/Header.js
  src/components/template/common/Navigation.js
  src/components/template/home/HomeFeed.js
  src/components/template/home/Search.js
  src/components/template/join/JoinEmail.js
  src/components/template/join/JoinProfile.js
  src/components/template/login/LoginEmail.js
  src/components/template/login/LoginMain.js
  src/components/template/post/PostUpload.js
  src/components/template/post/PostView.js
  src/components/template/product/ProductEdit.js
  src/components/template/product/ProductUpload.js
  src/components/template/profile/Follower.js
  src/components/template/profile/Profile.js
  src/components/template/profile/ProfileEdit.js
  src/components/template/screen/NotFound.js
  src/components/template/screen/SplashScreen.js
  src/styles/font.css
  src/styles/theme.js
Labels: 🪄 Feat, ⚙️ Setting

#41 add: 팔로우, 팔로잉 기능 추가
  src/App.js
  src/actions/followAction.js
  src/constants/followConstants.js
  src/hooks/useFollowButton.js
  src/hooks/useGNB.js
  src/pages/profile/Follower-gh/index.js
  src/pages/profile/Following-gh/index.js
  src/pages/profile/Myprofile-gh/index.js
  src/reducers/followReducer.js
  src/store.js
Labels: 🪄 Feat

#42 Bd/jisu
  src/components/NoneFeed.js
  src/components/module/form/LoginForm.js
  src/components/module/form/ProductForm.js
  src/components/module/form/ProfileForm.js
  src/components/module/form/RegisterForm.js
  src/components/module/logo/LoginLogo.js
  src/components/module/profile/ProfileIUpload.js
  src/components/module/user/SearchUser.js
  src/components/template/join/JoinEmail.js
  src/components/template/join/JoinProfile.js
  src/components/template/login/LoginEmail.js
  src/components/template/login/LoginMain.js
  src/components/template/product/ProductEdit.js
  src/components/template/product/ProductUpload.js
  src/components/template/profile/ProfileEdit.js
  src/pages/home/HomeMain/index.jsx
  src/pages/home/Search/index.jsx
Labels: :office: Build

#44 Add: Product 컴포넌트
  src/components/module/upload/UploadProfile.js
  src/components/template/product/ProductEdit.js
  src/components/template/product/ProductUpload.js
Labels: 🎨 Design

#46 Bd_Layoutcom
  src/components/MainLayOut.js
  src/components/module/Text/SubText.js
  src/components/template/chat/ChatList.js
  src/components/template/profile/ProfileEdit.js
  src/components/template/screen/NotFound.js
  src/components/template/screen/SplashScreen.js
Labels: 🎨 Design

#47 Bd: ChatRoom LayOut
  src/components/template/chat/ChatRoom.js
Labels: 🎨 Design

#48 Add: HomeFeed 레이아웃
  src/components/template/home/HomeFeed.js
Labels: 🎨 Design

#49 함수 변경
  src/components/Button.js
  src/components/DisplayHandler.js
  src/components/ImgRegister.js
  src/components/MainLayOut.js
  src/components/Post.js
  src/components/UploadPost.js
  src/components/template/chat/ChatList.js
  src/components/template/chat/ChatRoom.js
  src/components/template/common/Header.js
  src/components/template/common/Navigation.js
  src/components/template/home/HomeFeed.js
  src/components/template/home/Search.js
  src/components/template/join/JoinEmail.js
  src/components/template/join/JoinProfile.js
  src/components/template/login/LoginEmail.js
  src/components/template/login/LoginMain.js
  src/components/template/post/PostUpload.js
  src/components/template/post/PostView.js
  src/components/template/product/ProductEdit.js
  src/components/template/product/ProductUpload.js
  src/components/template/profile/Follower.js
  src/components/template/profile/Profile.js
  src/components/template/profile/ProfileEdit.js
  src/components/template/screen/NotFound.js
  src/components/template/screen/SplashScreen.js
Labels: 🛠 Refactoring

#50 fix: login-gh.js Button component import error
  src/pages/auth/LoginEmail-gh/index.js
Labels: 🐛 Fix Bug

#52 add: login form input 입력 시 버튼 활성화 기능 구현
  src/PAGE/LoginMain.jsx
  src/components/module/button/button.js
  src/components/module/form/LoginForm.js
  src/components/module/form/RegisterForm.js
  src/components/template/join/JoinEmail.js
  src/components/template/join/JoinProfile.js
  src/components/template/login/LoginEmail.js
  src/pages/auth/LoginEmail-gh/index.js
  src/pages/auth/LoginEmail/index.style.js
Labels: :office: Build

#51 Bd/jisu
  src/components/module/chat/Chat.js
  src/components/module/post/ReplyBox.js
  src/components/module/profile/ProfileIUpload.js
  src/components/module/user/ChatListUser.js
  src/components/module/user/FollowersUser.js
  src/components/template/chat/ChatList.js
  src/components/template/chat/ChatRoom.js
  src/components/template/join/JoinProfile.js
  src/components/template/post/PostView.js
  src/components/template/profile/Follower.js
  src/components/template/profile/Profile.js
  src/pages/post/PostView/index.style.js
Labels: :office: Build

#53 Bd/header com
  src/components/module/chat/Chat.js
  src/components/module/post/ReplyBox.js
  src/components/module/profile/ProfileIUpload.js
  src/components/module/user/ChatListUser.js
  src/components/module/user/FollowersUser.js
  src/components/template/chat/ChatList.js
  src/components/template/chat/ChatRoom.js
  src/components/template/common/Header.js
  src/components/template/home/HomeFeed.js
  src/components/template/home/Search.js
  src/components/template/join/JoinProfile.js
  src/components/template/post/PostUpload.js
  src/components/template/post/PostView.js
  src/components/template/product/ProductEdit.js
  src/components/template/product/ProductUpload.js
  src/components/template/profile/Follower.js
  src/components/template/profile/Profile.js
  src/components/template/profile/ProfileEdit.js
  src/pages/post/PostView/index.style.js
Labels: :office: Build

#55 Bd/nav com
  src/components/UserInfo.js
  src/components/module/Text/LoginText.js
  src/components/module/form/LoginForm.js
  src/components/module/form/RegisterForm.js
  src/components/module/title/LoginTitle.js
  src/components/module/user/CommentUser.js
  src/components/module/user/FollowersUser.js
  src/components/template/chat/ChatList.js
  src/components/template/chat/ChatRoom.js
  src/components/template/common/Header.js
  src/components/template/common/Navigation.js
  src/components/template/home/HomeFeed.js
  src/components/template/home/Search.js
  src/components/template/join/JoinEmail.js
  src/components/template/join/JoinProfile.js
  src/components/template/login/LoginMain.js
  src/components/template/post/PostView.js
  src/components/template/profile/Follower.js
  src/components/template/profile/Profile.js
  src/components/template/screen/NotFound.js
Labels: :office: Build

#57 Bd_product alert,modal
  src/components/UserInfo.js
  src/components/module/profile/ProfileIUpload.js
  src/components/template/profile/Profile.js
Labels: 🎨 Design

#59 Bd/product com
  src/components/module/logo/NotFoundLogo.js
  src/components/module/logo/SplashLogo.js
  src/components/module/product/Product.js
  src/components/template/profile/Profile.js
  src/components/template/screen/NotFound.js
  src/components/template/screen/SplashScreen.js
Labels: :office: Build

#62 Add: Api_Component
  src/App.js
  src/PAGE/FollowingList.jsx
  src/PAGE/PostView.jsx
  src/PAGE/ProfileUpdate.jsx
  src/PAGE/Search.jsx
  src/components/module/button/button.js
  src/components/module/form/ProfileForm.js
  src/components/module/post/ReplyBox.js
  src/components/module/user/FollowersUser.js
  src/components/module/user/SearchUser.js
  src/components/template/common/Header.js
  src/components/template/home/Search.js
  src/components/template/post/PostView.js
  src/components/template/profile/Follower.js
Labels: 🪄 Feat, 🎨 Design, :office: Build

#64 Fix_CommentUser
  src/PAGE/PostView.jsx
Labels: 🐛 Fix Bug, 🛠 Refactoring

#66 Bd_formCompo
  src/PAGE/LoginEmail.jsx
  src/PAGE/ProductUpdate.jsx
  src/components/module/button/button.js
Labels: 🛠 Refactoring

#68 Add : MainFieldSet추가
  src/PAGE/JoinProfile.jsx
Labels: :office: Build

#71 Bd/js
  src/PAGE/FollowerList.jsx
  src/PAGE/FollowingList.jsx
  src/PAGE/JoinProfile.jsx
  src/PAGE/LoginEmail.jsx
  src/PAGE/MyProfile.jsx
  src/PAGE/PostView.jsx
  src/PAGE/ProductUpdate.jsx
  src/PAGE/ProductUpload.jsx
  src/PAGE/ProfileUpdate.jsx
  src/PAGE/Search.jsx
  src/components/UserInfo.js
  src/components/module/post/ReplyBox.js
  src/styles/theme.js
Labels: :office: Build

#75 Bd/js
  src/PAGE/MyProfile.jsx
  src/PAGE/PostView.jsx
  src/components/common/image/ProfileImageStyle.js
  src/components/module/profile/UserInfo.js
Labels: :office: Build

#77 Fix: 불 필요한 코드 제거 및 에러 해결
  src/PAGE/JoinProfile.jsx
  src/components/module/button/button.js
  src/components/module/product/Product.js
  src/components/module/profile/DisplayButton.js
Labels: 🐛 Fix Bug

#78 Bd/js
  src/PAGE/MyProfile.jsx
  src/PAGE/PostView.jsx
  src/PAGE/YourProfile.jsx
  src/components/module/button/button.js
  src/components/module/profile/MyUserInfo.js
  src/components/module/profile/YourUserInfo.js
Labels: :office: Build

#83 add: yourProfile 데이터 바인딩
  package-lock.json
  src/App.js
  src/PAGE/JoinProfile.jsx
  src/PAGE/YourProfile.jsx
  src/actions/userActions.js
Labels: :office: Build

#84 fix: Myprofile YourProfile 프로필 이미지 오류 수정
  src/PAGE/MyProfile.jsx
  src/PAGE/YourProfile.jsx
Labels: 🐛 Fix Bug

#85 add: global navibar 추가 및 Notfound Page 연결
  src/App.js
  src/PAGE/FollowerList.jsx
  src/PAGE/FollowingList.jsx
  src/PAGE/Home.jsx
  src/PAGE/MyProfile.jsx
  src/PAGE/PostView.jsx
  src/PAGE/Search.jsx
  src/PAGE/YourProfile.jsx
Labels: :office: Build

#82 Fix style mj02
  src/PAGE/FollowerList.jsx
  src/PAGE/FollowingList.jsx
  src/PAGE/JoinProfile.jsx
  src/PAGE/LoginEmail.jsx
  src/PAGE/MyProfile.jsx
  src/PAGE/PostUpload.jsx
  src/PAGE/PostView.jsx
  src/PAGE/ProductUpdate.jsx
  src/PAGE/ProductUpload.jsx
  src/PAGE/ProfileUpdate.jsx
  src/PAGE/Search.jsx
  src/PAGE/SplashScreen.jsx
  src/PAGE/YourProfile.jsx
  src/actions/userActions.js
  src/asset/icon/full-logo.svg
  src/asset/icon/icon-home-fill.svg
  src/asset/icon/icon-message-circle-fill.svg
  src/asset/icon/icon-user-fill.svg
  src/asset/upload-file.svg
  src/components/module/post/ReplyBox.js
  src/components/module/product/Product.js
  src/components/template/common/Navigation.js
Labels: 🎨 Design, :office: Build

#86 fix: Home.jsx, JoinProfile, myProfile, PostUpload 오류 수정
  src/PAGE/Home.jsx
  src/PAGE/JoinProfile.jsx
  src/PAGE/MyProfile.jsx
  src/PAGE/PostUpload.jsx
  src/PAGE/ProductUpdate.jsx
  src/PAGE/ProductUpload.jsx
  src/actions/postActions.js
  src/actions/productActions.js
Labels: 🐛 Fix Bug

#88 Bd_headerSlider
  src/PAGE/Home.jsx
  src/components/module/post/ContentBox.js
Labels: :office: Build

#90 Add: 가격 원단위 변환 기능 추가
  src/PAGE/ProductUpload.jsx
Labels: 🪄 Feat, :office: Build

#91 Bd/js
  package-lock.json
  package.json
  src/PAGE/JoinProfile.jsx
  src/PAGE/LoginEmail.jsx
  src/PAGE/ProductUpdate.jsx
  src/PAGE/ProductUpload.jsx
  src/PAGE/ProfileUpdate.jsx
  src/actions/userActions.js
Labels: 🎨 Design, :office: Build

#93 Bd_display_handler
  src/PAGE/MyProfile.jsx
  src/PAGE/YourProfile.jsx
Labels: 🪄 Feat, :office: Build

#94 Api post view time
  public/favicon.ico
  public/index.html
  src/PAGE/PostView.jsx
  src/components/module/post/ReplyBox.js
  src/util/timeForToday.js
Labels: 🪄 Feat, :office: Build

#95 Add : yourprofile 버튼 추가
  src/PAGE/MyProfile.jsx
  src/PAGE/YourProfile.jsx
  src/components/module/button/button.js
Labels: 🎨 Design, :office: Build

#96 Fix : 팔로잉, 팔로워 마진 수정
  src/PAGE/FollowerList.jsx
  src/PAGE/FollowingList.jsx
  src/PAGE/ProductUpdate.jsx
  src/PAGE/ProductUpload.jsx
Labels: 🎨 Design, :office: Build

#97 Bd_button
  src/PAGE/Search.jsx
  src/PAGE/YourProfile.jsx
  src/components/module/button/button.js
Labels: 🐛 Fix Bug

#98 Bd_accessibility
  src/App.js
  src/PAGE/PostView.jsx
  src/PAGE/Search.jsx
  src/styles/GlobalStyles.js
Labels: 🐛 Fix Bug

#99 add: 회원가입 유효성검가 계정 검증 기능 추가
  src/PAGE/JoinProfile.jsx
  src/PAGE/MyProfile.jsx
  src/PAGE/PostView.jsx
  src/PAGE/ProductUpload.jsx
  src/actions/userActions.js
Labels: :office: Build

#100 add: 프로필 수정 페이지 계정 인증 기능 추가
  package-lock.json
  src/PAGE/JoinProfile.jsx
  src/PAGE/ProfileUpdate.jsx
  src/actions/userActions.js
  src/util/imageUploads.js
Labels: 🪄 Feat, :office: Build

#102 add: 로그인 인증 기능 추가
  src/PAGE/LoginEmail.jsx
  src/actions/userActions.js
Labels: 🪄 Feat

#101 Add : postview 라우팅 추가
  src/components/module/post/UserInfoBox.js
Labels: :office: Build

#103 Fix: 최신댓글 아래에서부터 업로드
  src/components/module/post/ReplyBox.js
Labels: 🐛 Fix Bug

#104 Bd style mj
  src/PAGE/JoinProfile.jsx
  src/PAGE/LoginEmail.jsx
  src/PAGE/MyProfile.jsx
  src/PAGE/PostUpload.jsx
  src/PAGE/ProfileUpdate.jsx
  src/asset/icon/icon-remove.svg
  src/components/module/product/Product.js
Labels: 🎨 Design, :office: Build

#106 Refector: product container
  src/PAGE/MyProfile.jsx
  src/PAGE/MyProfileJY.jsx
  src/components/Profile/ProductCard/index.jsx
  src/components/Profile/ProductCard/index.style.js
  src/components/Profile/ProductContainer/index.jsx
  src/components/Profile/ProductContainer/index.style.js
  src/components/Profile/ProfileContainer/index.jsx
Labels: 🛠 Refactoring

#107 fix: profileUpdate 유효성 평가 필수사항 수정
  src/PAGE/ProfileUpdate.jsx
  src/actions/userActions.js
Labels: 🐛 Fix Bug
