Repository Team-8px/earth_market, pull requests merged in 2022-01, with the labels that each got.

#2 Jy/add jslint prettier
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
Labels: Setting

#4 Add: ReadMe 파일 추가
  README.md
Labels: Document

#9 Jy/build join member ship
  src/App.js
  src/pages/auth/JoinMemberShip/index.jsx
  src/pages/auth/JoinMemberShip/index.style.js
  src/pages/auth/LoginMain/index.jsx
  src/pages/auth/LoginMain/index.style.js
  src/pages/auth/SetMemberShip/index.jsx
Labels: Publishing

#10 Jy/build product update
  src/components/MainLayOut.js
  src/pages/auth/JoinMemberShip/index.jsx
  src/pages/auth/LoginEmail/index.jsx
  src/pages/auth/LoginMain/index.jsx
  src/pages/auth/LoginMain/index.style.js
  src/pages/auth/SetMemberShip/index.jsx
  src/pages/auth/SetMemberShip/index.style.js
  src/pages/product/ProductUpload/index.jsx
  src/pages/product/ProductUpload/index.style.js
Labels: Publishing

#11 Jy/build lay out
  src/components/Button.js
  src/components/MainLayOut.js
  src/pages/auth/JoinMemberShip/index.jsx
  src/pages/auth/JoinMemberShip/index.style.js
  src/pages/auth/LoginEmail/index.jsx
  src/pages/auth/LoginEmail/index.style.js
  src/pages/auth/LoginMain/index.jsx
  src/pages/auth/LoginMain/index.style.js
  src/pages/auth/SetMemberShip/index.jsx
  src/pages/auth/SetMemberShip/index.style.js
  src/pages/chat/ChatList/index.jsx
  src/pages/chat/ChatList/index.style.js
  src/pages/chat/ChatRoom/index.jsx
  src/pages/chat/ChatRoom/index.style.js
  src/pages/home/HomeFeed/index.jsx
  src/pages/home/HomeFeed/index.style.js
  src/pages/home/HomeMain/index.jsx
  src/pages/home/HomeMain/index.style.js
  src/pages/home/Search/index.jsx
  src/pages/home/Search/index.style.js
  src/pages/post/PostUpload/index.jsx
  src/pages/post/PostUpload/index.style.js
  src/pages/post/PostView/index.jsx
  src/pages/post/PostView/index.style.js
  src/pages/product/ProductUpdate/index.jsx
  src/pages/product/ProductUpdate/index.style.js
  src/pages/product/ProductUpload/index.jsx
  src/pages/product/ProductUpload/index.style.js
  src/pages/profile/Follower/index.jsx
  src/pages/profile/Follower/index.style.js
  src/pages/profile/MyProfile/index.jsx
  src/pages/profile/MyProfile/index.style.js
  src/pages/profile/ProfileModification/index.jsx
  src/pages/profile/ProfileModification/index.style.js
  src/pages/profile/YourProfile/index.jsx
  src/pages/profile/YourProfile/index.style.js
  src/pages/screen/NotFound/index.jsx
  src/pages/screen/NotFound/index.style.js
  src/pages/screen/SplashScreen/index.jsx
  src/pages/screen/SplashScreen/index.style.js
Labels: Publishing

#14 fix: 충돌부분 해결
  package.json
  src/App.js
  src/pages/auth/JoinMemberShip/index.jsx
  src/pages/auth/LoginEmail/index.jsx
  src/pages/auth/LoginMain/index.jsx
  src/pages/auth/SetMemberShip/index.jsx
Labels: feature

#15 Jy/build post
  src/components/Comment.js
  src/components/Post.js
  src/components/comment/index.style.js
  src/pages/auth/SetMemberShip/index.style.js
  src/pages/home/HomeFeed/index.jsx
  src/pages/post/PostView/index.jsx
  src/pages/profile/MyProfile/index.jsx
  src/pages/profile/YourProfile/index.jsx
  src/styles/GlobalStyles.js
Labels: Publishing

#17 #1/Bd_ModalCom
  src/components/Alert.js
  src/components/HiddenMenu.js
  src/pages/profile/MyProfile/index.jsx
  src/pages/profile/YourProfile/index.jsx
Labels: 🪄 Feat, 🎨 Design, 🙋🏻 Require review

#18 #2/bd header com
  src/asset/icon-arrow-left.svg
  src/asset/icon-more-vertical.svg
  src/asset/icon-search.svg
  src/components/Header.js
  src/pages/auth/LoginEmail/index.jsx
  src/pages/auth/LoginMain/index.jsx
  src/pages/chat/ChatList/index.jsx
  src/pages/chat/ChatRoom/index.jsx
  src/pages/home/HomeFeed/index.jsx
  src/pages/home/HomeMain/index.jsx
  src/pages/home/Search/index.jsx
  src/pages/post/PostUpload/index.jsx
  src/pages/post/PostView/index.jsx
  src/pages/product/ProductUpdate/index.jsx
  src/pages/product/ProductUpload/index.jsx
  src/pages/profile/Follower/index.jsx
  src/pages/profile/MyProfile/index.jsx
  src/pages/profile/ProfileModification/index.jsx
  src/pages/profile/YourProfile/index.jsx
Labels: 🎨 Design

#21 #4/Bd_ButtonCom
  src/components/Button.js
  src/pages/auth/JoinMemberShip/index.jsx
  src/pages/auth/JoinMemberShip/index.style.js
  src/pages/auth/LoginEmail/index.jsx
  src/pages/auth/LoginEmail/index.style.js
  src/pages/auth/LoginMain/index.jsx
Labels: 🎨 Design

#22 #5/Bd_postupdateCom
  src/components/UploadPost.js
  src/pages/post/PostUpload/index.jsx
  src/pages/post/PostUpload/index.style.js
Labels: 🎨 Design

#24 Refactor img
  README.md
  src/components/Post.js
Labels: 🐛 Fix Bug

#26 Bd button com
  src/components/Button.js
  src/components/Header.js
  src/components/UserInfo.js
  src/pages/auth/JoinMemberShip/index.jsx
  src/pages/auth/LoginEmail/index.jsx
  src/pages/auth/SetMemberShip/index.jsx
  src/pages/home/HomeMain/index.jsx
  src/pages/post/PostUpload/index.jsx
  src/pages/product/ProductUpload/index.jsx
  src/pages/profile/Follower/index.jsx
  src/pages/screen/NotFound/index.jsx
Labels: 🎨 Design

#29 Bd_ModalCom
  src/App.js
  src/components/Alert.js
  src/components/Header.js
  src/components/HiddenMenu.js
  src/components/Post.js
  src/components/UserInfo.js
  src/pages/chat/ChatList/index.jsx
  src/pages/chat/ChatRoom/index.jsx
  src/pages/home/HomeFeed/index.jsx
  src/pages/post/PostView/index.jsx
  src/pages/post/PostView/index.style.js
  src/pages/profile/MyProfile/index.jsx
  src/pages/profile/YourProfile/index.jsx
Labels: 🎨 Design

#30 Bd_Theme Provider
  src/App.js
  src/components/MainLayOut.js
  src/index.js
  src/styles/theme.js
Labels: 🎨 Design

#31 Fix_LayOutCom
  src/components/Header.js
  src/components/MainLayOut.js
  src/components/UserInfo.js
  src/pages/home/HomeMain/index.style.js
  src/pages/home/Search/index.jsx
  src/pages/post/PostUpload/index.jsx
  src/pages/post/PostUpload/index.style.js
  src/pages/post/PostView/index.jsx
  src/pages/product/ProductUpload/index.jsx
  src/pages/profile/MyProfile/index.jsx
  src/pages/profile/ProfileModification/index.jsx
  src/pages/screen/NotFound/index.jsx
  src/pages/screen/NotFound/index.style.js
  src/pages/screen/SplashScreen/index.jsx
  src/pages/screen/SplashScreen/index.style.js
  src/styles/theme.js
Labels: 🎨 Design, 🐛 Fix Bug

#28 Bd_User_com
  src/components/ChatInfoList.js
  src/components/FollowerList.js
  src/components/NoneFeed.js
  src/components/UserList.js
  src/pages/chat/ChatList/index.jsx
  src/pages/chat/ChatList/index.style.js
  src/pages/chat/ChatRoom/index.jsx
  src/pages/chat/ChatRoom/index.style.js
  src/pages/home/HomeMain/index.jsx
  src/pages/home/HomeMain/index.style.js
  src/pages/home/Search/index.jsx
  src/pages/home/Search/index.style.js
  src/pages/product/ProductUpdate/index.jsx
  src/pages/profile/Follower/index.jsx
  src/pages/profile/Follower/index.style.js
Labels: 🎨 Design

#32 Add : UserInfo 컴포넌트 수정
  src/components/UserInfo.js
  src/components/common/image/ProfileImageStyle.js
  src/pages/post/PostView/index.jsx
  src/pages/post/PostView/index.style.js
  src/pages/profile/ProfileModification/index.jsx
Labels: 🎨 Design

#35 Bd image&lay out com
  src/components/FollowerList.js
  src/components/Header.js
  src/components/ImgRegister.js
  src/components/MainLayOut.js
  src/pages/product/ProductUpdate/index.jsx
  src/pages/product/ProductUpdate/index.style.js
  src/pages/product/ProductUpload/index.jsx
  src/pages/product/ProductUpload/index.style.js
  src/pages/profile/Follower/index.jsx
  src/styles/GlobalStyles.js
  src/styles/theme.js
Labels: 🎨 Design, 🐛 Fix Bug

#36 Fix: 에러 해결 및 파일 위치 변경
  src/asset/font/SpoqaHanSansNeo-Bold.woff
  src/asset/font/SpoqaHanSansNeo-Medium.woff
  src/asset/font/SpoqaHanSansNeo-Regular.woff
  src/pages/profile/MyProfile/index.jsx
Labels: ⚙️ Setting, 🐛 Fix Bug

#37 Bd comment com
  src/pages/chat/ChatList/index.jsx
  src/pages/chat/ChatRoom/index.jsx
  src/pages/home/HomeFeed/index.jsx
  src/pages/home/HomeMain/index.jsx
  src/pages/home/Search/index.jsx
  src/pages/post/PostView/index.jsx
  src/pages/profile/Follower/index.jsx
  src/pages/profile/MyProfile/index.jsx
  src/pages/profile/YourProfile/index.jsx
  src/pages/screen/NotFound/index.jsx
Labels: 🎨 Design
